# 基础配置
mixed-port: 7890
allow-lan: true
bind-address: "*"
ipv6: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

# DNS配置
dns:
  enable: true
  prefer-h3: true
  use-hosts: true
  use-system-hosts: true
  respect-rules: false
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "+.local"
    - localhost.ptlogin2.qq.com
  default-nameserver:
    - tls://1.12.12.12
    - 223.5.5.5
    - 119.29.29.29
  nameserver-policy:
    "www.baidu.com": "114.114.114.114"
    "+.internal.crop.com": "10.0.0.1"
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - tls://1dot1dot1dot1.cloudflare-dns.com
    - tcp://1.1.1.1
    - https://1.0.0.1/dns-query
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"

# 代理集和规则集缓存时间
profile:
  store-selected: true
  store-fake-ip: true

# tun模式配置
tun:
  enable: true
  stack: system
  dns-hijack:
    - "any:53"
  auto-route: true
  auto-detect-interface: true


# 空白代理组配置（由脚本生成）
# 🎯 自定义直连  # 🚀 节点选择  # 🚀 手动切换  # ♻️ 自动选择
# 📲 电报消息    # 💬 OpenAi  # 📹 油管视频  # 🎥 奈飞视频
# 📺 巴哈姆特    # 📺 哔哩哔哩  # 🌍 国外媒体  # 🌏 国内媒体
# 📢 谷歌FCM    # Ⓜ️ 微软Bing  # Ⓜ️ 微软云盘  # Ⓜ️ 微软服务
# 🍎 苹果服务   # 🎮 游戏平台  # 🎶 网易音乐  # 🎯 全球直连
# 🛑 广告拦截   # 🍃 应用净化  # 🐟 漏网之鱼  # 🎥 奈飞节点
# 🇭🇰 香港节点   # 🇨🇳 台湾节点  # 🇯🇵 日本节点  # 🇺🇲 美国节点
# 🇸🇬 狮城节点   # 🇰🇷 韩国节点

rules: ["DOMAIN-SUFFIX,linux.do,🎯 自定义直连"]
